---
version: "3.3"

services:

  # Puppeteer to do the html => pdf conversion
  puppeteer:
    build: ./docker_pdf
    ports:
      - "5000:5000"
    volumes:
      - ..:/builder/shared
    command: 
      - wait-for-it
      - "site:1313"
      - --
      - node
      - ../generate_pdf.js

  # Hugo server to serve up the docs
  site:
    image: docsy/docsy-example
    build:
      context: ../
    command: server
    ports:
      - "1313:1313"
    volumes:
      - ..:/src
